# Export some variable found by CMake


PARFLOW_VERSION_STRING="v3.12.0-20-gc500eb7"
PARFLOW_VERSION="3.12.0"
PARFLOW_VERSION_MAJOR=3
PARFLOW_VERSION_MINOR=12
PARFLOW_VERSION_PATCH=0
PARFLOW_VERSION_HASH="c500eb7"
PARFLOW_VERSION_EXTRA="20"

MPIEXEC=""
MPIEXEC_NUMPROC_FLAG=""
MPIEXEC_POSTFLAGS=""
MPIEXEC_PREFLAGS=""
